
#http://myzuul.com:9527/springcloud-dept/dept/get/2  没有配置路由的时候需要这样访问
#配置路由之后可以通过 http://myzuul.com:9527/mydept/dept/get/2 进行访问

server:
  port: 9527
  
spring:
  application:
    name: springcloud-zuul-gateway
      
eureka:
  client:  #客户端注册eureka服务
    service-url:
      #defaultZone: http://localhost:7001/eureka      
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka       
  instance: #设置别名
    instance-id: gateway-9527.com   #自定义hystrix服务名称信息
    prefer-ip-address: true       #访问路径可以显示IP地址
    
zuul:
  routes:
    mydept.serviceId: springcloud-dept   #配置映射地址
    mydept.path: /mydept/**
  ignored-services: "*" #忽略所有的服务
  prefix: /gjb          #设置统一公共前缀   http://myzuul.com:9527/gjb/mydept/dept/get/2
  #ignored-services: springcloud-dept #忽略真实的微服务名称 支持多个
     
    
    
    
info: #配置点击服务之后显示详细信息
   app.name: springcloud
   company.name: zhongchi
   build.artifactId: $project.artifactId$
   build.version: $project.version$
   
   
   

   
   
   
   
   
   
   
   
   
   
   